driver:
  name: ec2
  aws_ssh_key_id: <%= ENV['AWS_SSH_KEY'] %>
  security_group_ids:  <%= ENV['AWS_SECURITY_GROUPS'] %>
  region: <%= ENV['AWS_REGION'] %>
  availability_zone: <%= ENV['AWS_AVAILABILITY_ZONE'] %>
  require_chef_omnibus: true
  subnet_id: <%= ENV['AWS_SUBNET'] %>
  associate_public_ip: false
  interface: private
  tags:
    OWNER: <%= ENV['AWS_OWNER_TAG'] %>

provisioner:
  name: chef_zero
  attributes:
    firewall:
      allow_ssh: true
      allow_winrm: true
      firewalld:
        permanent: true

transport:
  ssh_key: <%= ENV['SSH_KEY_PATH'] %><%= ENV['AWS_SSH_KEY'] %>.pem

platforms:
  - name: centos-5.11
    driver:
      image_id: <%= ENV['AWS_CENTOS5_AMI_ID'] %>
      instance_type: <%= ENV['LINUX_INSTANCE_SIZE'] %>
      user_data: <%= ENV['LINUX_USER_DATA_PATH'] %>
    transport:
      username: <%= ENV['AWS_CENTOS5_USERNAME'] %>
  - name: centos-6.7
    driver:
      image_id: <%= ENV['AWS_CENTOS6_AMI_ID'] %>
      instance_type: <%= ENV['LINUX_INSTANCE_SIZE'] %>
      user_data: <%= ENV['LINUX_USER_DATA_PATH'] %>
    transport:
      username: <%= ENV['AWS_CENTOS6_USERNAME'] %>
  - name: centos-7.1
    driver:
      image_id: <%= ENV['AWS_CENTOS7_AMI_ID'] %>
      instance_type: <%= ENV['LINUX_INSTANCE_SIZE'] %>
      user_data: <%= ENV['LINUX_USER_DATA_PATH'] %>
    transport:
      username: <%= ENV['AWS_CENTOS7_USERNAME'] %>
  - name: debian-7.8
    run_list:
      - recipe[apt]
  - name: debian-8.1
    run_list:
      - recipe[apt]
  - name: ubuntu-12.04
    driver:
      image_id: <%= ENV['AWS_UBUNTU12_AMI_ID'] %>
      instance_type: <%= ENV['LINUX_INSTANCE_SIZE'] %>
      user_data: <%= ENV['LINUX_USER_DATA_PATH'] %>
    transport:
      username: <%= ENV['AWS_UBUNTU12_USERNAME'] %>
    run_list:
      - recipe[apt::default]
  - name: ubuntu-14.04
    driver:
      image_id: <%= ENV['AWS_UBUNTU14_AMI_ID'] %>
      instance_type: <%= ENV['LINUX_INSTANCE_SIZE'] %>
      user_data: <%= ENV['LINUX_USER_DATA_PATH'] %>
    transport:
      username: <%= ENV['AWS_UBUNTU14_USERNAME'] %>
    run_list:
      - recipe[apt::default]
  - name: windows-2012r2
    driver:
      image_id: <%= ENV['AWS_WINDOWS2012R2_AMI_ID'] %>
      instance_type: <%= ENV['WINDOWS_INSTANCE_SIZE'] %>
      user_data: <%= ENV['WINDOWS_USER_DATA_PATH'] %>
    transport:
      name: winrm

suites:
  - name: default
    run_list:
      - recipe[firewall::default]
      - recipe[firewall-test::default]
    excludes:
      - centos-5.11
      - ubuntu-12.04
      - debian-7.8
      - debian-8.1
  - name: iptables
    excludes:
      - centos-5.11
      - centos-6.7
      - debian-7.8
      - debian-8.1
      - windows-2012r2
    run_list:
      - recipe[firewall-test::default]
    attributes:
      firewall:
        ubuntu_iptables: true
        redhat7_iptables: true
